### ISSUE TITLE
EOF end of file reached

### ISSUE THREAD

**Issue by mhluska** [piotrmurach/rspec-benchmark#9]
### Are you in the right place?
* For issues or feature requests file a GitHub issue in this repository
* For general questions or discussion post on StackOverflow

### Describe the problem
I get this error:

```rb
     Failure/Error: expect { 1000.times { subject.update_transactions_for(payment) } }.to perform_under(50).ms

     EOFError:
       end of file reached
     # /Users/mhluska/.rvm/gems/ruby-2.5.1/gems/benchmark-perf-0.4.0/lib/benchmark/perf/execution_time.rb:50:in `load'
     # /Users/mhluska/.rvm/gems/ruby-2.5.1/gems/benchmark-perf-0.4.0/lib/benchmark/perf/execution_time.rb:50:in `run_in_subprocess'
     # /Users/mhluska/.rvm/gems/ruby-2.5.1/gems/benchmark-perf-0.4.0/lib/benchmark/perf/execution_time.rb:65:in `block in run_warmup'
     # /Users/mhluska/.rvm/gems/ruby-2.5.1/gems/benchmark-perf-0.4.0/lib/benchmark/perf/execution_time.rb:64:in `times'
     # /Users/mhluska/.rvm/gems/ruby-2.5.1/gems/benchmark-perf-0.4.0/lib/benchmark/perf/execution_time.rb:64:in `run_warmup'
     # /Users/mhluska/.rvm/gems/ruby-2.5.1/gems/benchmark-perf-0.4.0/lib/benchmark/perf/execution_time.rb:87:in `run'
     # /Users/mhluska/.rvm/gems/ruby-2.5.1/gems/rspec-benchmark-0.4.0/lib/rspec/benchmark/timing_matcher.rb:42:in `matches?'
     # ./spec/acceptance/commands/payment_processor_spec.rb:16:in `block (3 levels) in <top (required)>
```

### Steps to reproduce the problem

My RSpec test:
```rb
require 'active_record'
require 'cryptocoin_payable/commands/payment_processor'
require 'cryptocoin_payable/coin_payment'

describe CryptocoinPayable::PaymentProcessor do
  context 'when testing performance of database operations' do
    before(:all) { GC.disable }
    after(:all) { GC.enable }

    before do
      ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: 'spec/dummy/db/test.sqlite3')
    end

    it 'should update transactions 1000 times in under 50ms' do
      payment = CryptocoinPayable::CoinPayment.new(address: '3HR9xYD7MybbE7JLVTjwijYse48BtfEKni', coin_type: :btc)
      expect { 1000.times { subject.update_transactions_for(payment) } }.to perform_under(50).ms
    end
  end
end
```

To run this code:
```sh
git clone git@github.com:Sailias/cryptocoin_payable.git
cd cryptocoin_payable
git checkout use-bulk-insertion
git pull
bundle install
rspec
```

### Actual behaviour
EOFError raised

### Expected behaviour
Timing results returned.

### Describe your environment

* OS version: Mac High Sierra 10.13.6
* Ruby version: Tried 2.4.0 and 2.5.1
* RSpec version: 3.7.0
* RSpec::Benchmark version: 3.7.0

**Comment by mhluska** [comment]
If I replace, `expect { 1000.times { subject.update_transactions_for(payment) } }.to perform_under(50).ms` with `expect { 1000.times { 'a' + 'b' } }.to perform_under(50).ms`, it passes.

**Comment by mhluska** [comment]
This seems to be related to an external request being made. Once I added VCR, things worked fine.
